config:
  seed: 42
  dataset:
    name: FashionMNIST
    root: ./data
    batch_size: 128
    num_workers: 4
    val_split: 0.2
    normalize:
      mean:
      - 0.5
      std:
      - 0.5
  model:
    latent_dim: 64
    learning_rate: 0.001
    weight_decay: 1.0e-05
  trainer:
    max_epochs: 50
    accelerator: auto
    devices: 1
    log_every_n_steps: 50
    gradient_clip_val: 0.5
    precision: 32
    check_val_every_n_epoch: 1
  visualization:
    num_samples: 10
    epoch_interval: 5
    save_dir: visualization_results
