dataset:
  name: "FashionMNIST" # Nombre del dataset
  root: "./data" # Directorio raíz para datos
  batch_size: 128 # Tamaño del batch
  num_workers: 4 # Número de trabajadores para carga de datos
  val_split: 0.2 # Porcentaje de datos para validación
  normalize:
    mean: [0.5] # Media para normalización (no utilizada en código actual)
    std: [0.5] # Desviación estándar para normalización (no utilizada)
