defaults:
  - model: default # Configuración del modelo por defecto
  - dataset: fashion_mnist # Configuración específica para FashionMNIST
  - trainer: default # Configuración del entrenador por defecto
  - visualization: default # Configuración de visualización por defecto
  - _self_ # Indica que este archivo puede sobrescribir configuraciones previas

seed: 42 # Semilla para reproducibilidad

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} # Directorio para salidas de ejecución
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S} # Directorio para ejecuciones múltiples
    subdir: ${hydra.job.num} # Subdirectorio para cada trabajo
